/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AtChar123handleChar125RouteImport } from './routes/@{$handle}'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as PopularRouteImport } from './routes/popular'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as FeedbacksIdRouteImport } from './routes/feedbacks.$id'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as MissionsIdReportRouteImport } from './routes/missions.$id.report'
import { Route as ProjectsIdEditRouteImport } from './routes/projects.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AtChar123handleChar125Route = AtChar123handleChar125RouteImport.update({
  id: '/@{$handle}',
  path: '/@{$handle}',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PopularRoute = PopularRouteImport.update({
  id: '/popular',
  path: '/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbacksIdRoute = FeedbacksIdRouteImport.update({
  id: '/feedbacks/$id',
  path: '/feedbacks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsIdReportRoute = MissionsIdReportRouteImport.update({
  id: '/missions/$id/report',
  path: '/missions/$id/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdEditRoute = ProjectsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/@{$handle}': typeof AtChar123handleChar125Route
  '/inbox': typeof InboxRoute
  '/popular': typeof PopularRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/feedbacks/$id': typeof FeedbacksIdRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/missions/$id/report': typeof MissionsIdReportRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/@{$handle}': typeof AtChar123handleChar125Route
  '/inbox': typeof InboxRoute
  '/popular': typeof PopularRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/feedbacks/$id': typeof FeedbacksIdRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/missions/$id/report': typeof MissionsIdReportRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/@{$handle}': typeof AtChar123handleChar125Route
  '/inbox': typeof InboxRoute
  '/popular': typeof PopularRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/feedbacks/$id': typeof FeedbacksIdRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/missions/$id/report': typeof MissionsIdReportRoute
  '/projects/$id/edit': typeof ProjectsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/@{$handle}'
    | '/inbox'
    | '/popular'
    | '/settings'
    | '/sign-in'
    | '/feedbacks/$id'
    | '/projects/$id'
    | '/projects/new'
    | '/missions/$id/report'
    | '/projects/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/@{$handle}'
    | '/inbox'
    | '/popular'
    | '/settings'
    | '/sign-in'
    | '/feedbacks/$id'
    | '/projects/$id'
    | '/projects/new'
    | '/missions/$id/report'
    | '/projects/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/@{$handle}'
    | '/inbox'
    | '/popular'
    | '/settings'
    | '/sign-in'
    | '/feedbacks/$id'
    | '/projects/$id'
    | '/projects/new'
    | '/missions/$id/report'
    | '/projects/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AtChar123handleChar125Route: typeof AtChar123handleChar125Route
  InboxRoute: typeof InboxRoute
  PopularRoute: typeof PopularRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  FeedbacksIdRoute: typeof FeedbacksIdRoute
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  MissionsIdReportRoute: typeof MissionsIdReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/@{$handle}': {
      id: '/@{$handle}'
      path: '/@{$handle}'
      fullPath: '/@{$handle}'
      preLoaderRoute: typeof AtChar123handleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popular': {
      id: '/popular'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof PopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedbacks/$id': {
      id: '/feedbacks/$id'
      path: '/feedbacks/$id'
      fullPath: '/feedbacks/$id'
      preLoaderRoute: typeof FeedbacksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/$id/report': {
      id: '/missions/$id/report'
      path: '/missions/$id/report'
      fullPath: '/missions/$id/report'
      preLoaderRoute: typeof MissionsIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/edit': {
      id: '/projects/$id/edit'
      path: '/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof ProjectsIdEditRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
  }
}

interface ProjectsIdRouteChildren {
  ProjectsIdEditRoute: typeof ProjectsIdEditRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdEditRoute: ProjectsIdEditRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AtChar123handleChar125Route: AtChar123handleChar125Route,
  InboxRoute: InboxRoute,
  PopularRoute: PopularRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  FeedbacksIdRoute: FeedbacksIdRoute,
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  MissionsIdReportRoute: MissionsIdReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../src/router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
