export type { RecordedMail } from './console-mailer'
export { ConsoleMailer } from './console-mailer'
export { MailModule, mailerFor } from './mail.module'
export type { ResendConfig } from './resend-mailer'
export { RESEND_ENDPOINT, ResendMailer } from './resend-mailer'
export { SendEmailJob } from './send-email.job'
